### ISSUE TITLE
How can I implement the event Calendar in a CMS page?

### ISSUE THREAD

**Issue by EnigmaWebdesign** [cakemanny/magento-events#1]
Hi all,

This might be a little late question but...
How can I add the events on the frontend in a CMS page?

Br,

Steve

**Comment by cakemanny** [comment]
Hi Steve,

If I remember correctly, the events have to be added in the backoffice admin panel.
There's no support for frontend editing. I'm afraid I don't know anything about frontend CMS pages.

I'm not used Magento for 7 years, so I'll be surprised if this extension still works at all.
But good luck

**Comment by cakemanny** [comment]
Hi Steve,

If I remember correctly, the events have to be added in the backoffice admin panel.
There's no support for frontend editing. I'm afraid I don't know anything about frontend CMS pages.

I'm not used Magento for 7 years, so I'll be surprised if this extension still works at all.
But good luck
